# 日志配置
log_level: ${LOG_LEVEL}  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL

# CSV 文件配置
csv_file_path: ${CSV_FILE_PATH}

# MySQL 数据库配置
mysql:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  database: ${DB_NAME}
  table: ${DB_TABLE}
